apiVersion: v1
kind: ConfigMap
metadata:
  name: skyops-config
  namespace: skyops
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  VLLM_BASE_URL: "http://vllm:8001/v1"
  LLM_MODEL_ID: "aviation-llm"
  OTEL_ENABLED: "1"
  OTEL_SERVICE_NAME: "skyops-api"
  OTEL_CONSOLE_EXPORTER: "0"
  OTEL_OTLP_EXPORTER: "1"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.observability.svc.cluster.local:4317"
  DEPLOY_ENV: "production"
