"""SkyOps Feast Feature Views (P6-A).

P1 rotation features + P2 phase + P5+ SWIM NOTAM을 Feature View로 정리.

Why Feature Views?
------------------
Strategic Review 병목 #6 (training-serving skew). 학습 시
`feature_engineering.py` 에서 계산한 rotation feature 와 서빙 시
`serving/routers/delay.py`에서 DelayRequest로 받는 것이 완전히 같은
정의여야 한다. Feature View 가 이 "하나의 진실"을 강제한다.

Training:
  fs.get_historical_features(entity_df=train_df, features=[...])
  → point-in-time correct join

Serving:
  fs.get_online_features(entity_rows=[{tail: 'N12345'}], features=[...])
  → Redis 에서 같은 feature 를 꺼내오기
"""
from __future__ import annotations

from datetime import timedelta
from pathlib import Path

from feast import FeatureView, Field, FileSource
from feast.types import Float32, Int32, String

from .entities import aircraft_entity, airport_entity, flight_entity, icao24_entity


PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = PROJECT_ROOT / "data"

# ── Data Sources ──────────────────────────────────────────────────────

# P1 Rotation features (precomputed, offline)
rotation_source = FileSource(
    name="rotation_source",
    path=str(DATA_DIR / "processed" / "rotation_features.parquet"),
    timestamp_field="event_timestamp",
    created_timestamp_column="created_timestamp",
    description="Per-leg rotation features from analysis/feature_engineering.py",
)

# Live ADS-B (streaming — materialized periodically)
live_position_source = FileSource(
    name="live_position_source",
    path=str(DATA_DIR / "feast" / "live_position.parquet"),
    timestamp_field="event_timestamp",
    description="Latest position snapshot per icao24 (from Flink processor)",
)

# Airport congestion (rolling window)
airport_congestion_source = FileSource(
    name="airport_congestion_source",
    path=str(DATA_DIR / "feast" / "airport_congestion.parquet"),
    timestamp_field="event_timestamp",
    description="Hourly departure/arrival counts per airport",
)

# NOTAM operational impact (from swim_subscriber output)
notam_impact_source = FileSource(
    name="notam_impact_source",
    path=str(DATA_DIR / "feast" / "notam_impact.parquet"),
    timestamp_field="event_timestamp",
    description="Airport-level NOTAM impact score from FAA SWIM feed",
)

# v2.1.9 · ADR-005 Stage 2 ─ Network topology (static, refreshed monthly)
airport_graph_source = FileSource(
    name="airport_graph_source",
    path=str(DATA_DIR / "feast" / "airport_graph.parquet"),
    timestamp_field="event_timestamp",
    description=(
        "Static per-airport topology (pagerank, betweenness, hub score). "
        "Generated by analysis/graph_features.py on the full flights corpus. "
        "Refresh cadence = monthly. Parquet views of data/models/graph_features_airports.csv."
    ),
)

# v2.1.9 · ADR-005 Stage 2 ─ Rolling upstream delay state (streaming → feast materialize)
upstream_delay_source = FileSource(
    name="upstream_delay_source",
    path=str(DATA_DIR / "feast" / "upstream_delay.parquet"),
    timestamp_field="event_timestamp",
    description=(
        "Rolling-60min delay state per airport (avg / p95 / volume / congestion ratio). "
        "Offline: analysis/upstream_delay.py; online: Redis hash `skyops:upstream:{airport}`."
    ),
)


# ── Feature Views ─────────────────────────────────────────────────────

flight_rotation_fv = FeatureView(
    name="flight_rotation",
    entities=[aircraft_entity],
    ttl=timedelta(hours=24),
    schema=[
        Field(name="rotation_depth", dtype=Int32,
              description="# of legs this tail has flown today"),
        Field(name="prev_leg_arr_delay_min", dtype=Float32,
              description="Previous leg arrival delay in minutes"),
        Field(name="scheduled_turnaround_min", dtype=Float32,
              description="Scheduled gate turnaround time"),
        Field(name="actual_turnaround_min", dtype=Float32,
              description="Actual gate turnaround time (rolling avg)"),
        Field(name="is_first_leg_of_day", dtype=Int32,
              description="1 if first leg of calendar day"),
    ],
    source=rotation_source,
    online=True,
    tags={
        "owner": "skyops-ml-team",
        "domain": "delay_prediction",
        "source_sprint": "P1",
    },
    description="P1 Rotation feature set — drives Test R² from 0.10 to 0.43",
)


live_position_fv = FeatureView(
    name="live_position",
    entities=[icao24_entity],
    ttl=timedelta(minutes=5),  # ADS-B는 short TTL
    schema=[
        Field(name="baro_altitude", dtype=Float32),
        Field(name="velocity", dtype=Float32),
        Field(name="vertical_rate", dtype=Float32),
        Field(name="on_ground", dtype=Int32),
        Field(name="flight_phase", dtype=String,
              description="TAXI/TAKEOFF/CLIMB/CRUISE/DESCENT/APPROACH/LANDING"),
        Field(name="phase_confidence", dtype=Float32),
    ],
    source=live_position_source,
    online=True,
    tags={
        "owner": "skyops-streaming-team",
        "domain": "anomaly_detection",
        "source_sprint": "P2",
    },
    description="Live ADS-B snapshot — ML phase classifier output",
)


airport_congestion_fv = FeatureView(
    name="airport_congestion",
    entities=[airport_entity],
    ttl=timedelta(hours=6),
    schema=[
        Field(name="hourly_departures", dtype=Int32),
        Field(name="hourly_arrivals", dtype=Int32),
        Field(name="avg_taxi_out_min", dtype=Float32),
        Field(name="avg_taxi_in_min", dtype=Float32),
    ],
    source=airport_congestion_source,
    online=True,
    tags={
        "owner": "skyops-ml-team",
        "domain": "delay_prediction",
        "source_sprint": "P1",
    },
    description="Rolling-hour airport congestion metrics",
)


notam_impact_fv = FeatureView(
    name="notam_impact",
    entities=[airport_entity],
    ttl=timedelta(hours=12),
    schema=[
        Field(name="active_notam_count", dtype=Int32),
        Field(name="runway_closure_count", dtype=Int32),
        Field(name="navaid_outage_count", dtype=Int32),
        Field(name="notam_impact_score", dtype=Float32,
              description="Weighted operational impact 0-1"),
    ],
    source=notam_impact_source,
    online=True,
    tags={
        "owner": "skyops-streaming-team",
        "domain": "operational_context",
        "source_sprint": "P5+",
    },
    description="Aggregated NOTAM operational impact from FAA SWIM",
)


# v2.1.9 · ADR-005 Stage 2 — Airport network topology feature view.
airport_graph_fv = FeatureView(
    name="airport_graph",
    entities=[airport_entity],
    ttl=timedelta(days=30),  # topology 는 월 단위로 refresh
    schema=[
        Field(name="degree_in", dtype=Int32,
              description="얼마나 많은 공항이 이 공항으로 들어오는가"),
        Field(name="degree_out", dtype=Int32,
              description="얼마나 많은 공항으로 출발하는가"),
        Field(name="degree_total", dtype=Int32),
        Field(name="pagerank", dtype=Float32,
              description="Weighted PageRank — 네트워크 전체 중요도"),
        Field(name="betweenness", dtype=Float32,
              description="최단경로 중개성 — 허브 성격"),
        Field(name="airport_hub_score", dtype=Float32,
              description="log1p(degree_total) × (1+pagerank) 복합 hub 지표"),
    ],
    source=airport_graph_source,
    online=True,
    tags={
        "owner": "skyops-ml-team",
        "domain": "delay_prediction",
        "source_sprint": "Stage 2",
    },
    description="Static airport network topology — ADR-005 D2",
)


# v2.1.9 · ADR-005 Stage 2 — Upstream delay state (leak-free rolling).
upstream_delay_fv = FeatureView(
    name="upstream_delay",
    entities=[airport_entity],
    ttl=timedelta(minutes=75),  # 60min 윈도우 + 15min buffer
    schema=[
        Field(name="origin_recent_delay_avg_60m", dtype=Float32),
        Field(name="origin_recent_delay_p95_60m", dtype=Float32),
        Field(name="origin_recent_volume_60m", dtype=Int32),
        Field(name="dest_recent_delay_avg_60m", dtype=Float32),
        Field(name="dest_recent_volume_60m", dtype=Int32),
        Field(name="origin_hub_congestion_ratio", dtype=Float32),
    ],
    source=upstream_delay_source,
    online=True,
    tags={
        "owner": "skyops-ml-team",
        "domain": "delay_prediction",
        "source_sprint": "Stage 2",
    },
    description=(
        "Rolling-60min upstream delay/volume per airport. "
        "Leak-free at training (closed='left'), O(1) lookup at serving."
    ),
)


# ── Feature Services (bundles used by a specific model/endpoint) ──────

from feast import FeatureService  # noqa: E402

delay_prediction_v2 = FeatureService(
    name="delay_prediction_v2",
    features=[
        flight_rotation_fv,
        airport_congestion_fv,
        notam_impact_fv,
    ],
    description="Features consumed by /predict/delay (XGBoost + Conformal)",
    tags={"model": "xgboost_best", "version": "2.1.0"},
)

# v2.1.9 · ADR-005 Stage 2 — Network-aware candidate bundle.
# `delay_prediction_v2` 는 현 production 모델용, `delay_prediction_v3_network`
# 은 **다음 retrain 의 input** 으로 준비된 bundle. Training pipeline 이 이 서비스를
# 참조해야 변경된 feature set 과 unlock 되는 모델 버전이 연결된다.
delay_prediction_v3_network = FeatureService(
    name="delay_prediction_v3_network",
    features=[
        flight_rotation_fv,
        airport_congestion_fv,
        notam_impact_fv,
        airport_graph_fv,
        upstream_delay_fv,
    ],
    description=(
        "Stage 2 candidate feature bundle — rotation + static graph topology "
        "+ upstream delay state. Consumed by next XGBoost retrain (not yet production)."
    ),
    tags={"model": "xgboost_network", "version": "3.0.0-candidate"},
)

anomaly_detection_v2 = FeatureService(
    name="anomaly_detection_v2",
    features=[
        live_position_fv,
    ],
    description="Features consumed by /detect/anomaly (per-phase IF)",
    tags={"model": "isolation_forest_per_phase", "version": "2.1.0"},
)


# Public registry (consumed by `feast apply` and `feature_store.apply`)
ALL_ENTITIES = [aircraft_entity, airport_entity, flight_entity, icao24_entity]
ALL_FEATURE_VIEWS = [
    flight_rotation_fv,
    live_position_fv,
    airport_congestion_fv,
    notam_impact_fv,
]
ALL_FEATURE_SERVICES = [delay_prediction_v2, anomaly_detection_v2]
